services:
  develop:
    build: .
    ports:
      - "3000:3000"
    container_name: fw-service-template
    volumes:
      - ./app:/opt/fw-service-template/app
      - ./config:/opt/fw-service-template/config
      - ./nodemon.json:/opt/fw-service-template/nodemon.json
    command: yarn dev
